exports.MSG_CONSTANTS = {
    EMAIL_EXISTS: 'This Email Already Exists',
    USERNAME_EXISTS: 'This Username Already Exists',
    REGISTER_SUCCESS: 'Register Successfully',
    LOGIN_SUCCESS: 'Login Successfully',
    ERROR_REGISTER_SUCCESS: 'Error in User Register ',
    WRONG_PASSWORD: 'Wrong Passsword',
    NO_USER_FOUND: 'No User found.',
    ERROR_OAUTH_GOOGLE: 'OAUth Login for google fails.',
    CATEGORY_ADDED: 'Category Added Successfully',
    ERROR_CATEGORY_ADDED: 'Error in category Added',
    CATEGORY_NOT_FOUND: 'Category Not Found',
    CATEGORY_FETCHED: 'Category Found.',
    ERROR_FOUND_CATEGORY: 'Error in Category Found',
    ERROR_UPDATE_CATEGORY: 'Error in Category Updation',
    UPDATE_CATEGORY: 'Category Updated Successfully',
    CATEGORY_DELETED: 'Category Deleted Successfully',
    ERROR_DELETE_CATEGORY: 'Error in Category Deleted',
    CONTENT_ADDED: 'Content Added Successfully',
    ERROR_ADD_CONTENT: 'Error in Content adding.',
    CONTENT_NOT_FOUND: 'Content not Found',
    CONTENT_FOUND: 'Content Found',
    ERROR_CONTENT_FOUND: 'Error in content found',
    CONTENT_UPDATED: 'Content Updated Successfully',
    ERROR_CONTENT_UPDATED: 'Error in content Updated',
    DELETE_CONTENT: 'Delete Content Sccessfully',
    ERROR_DELETE_CONTENT: 'Error in Delete Content ',
    IMAGE_FETCHED: 'Image Fetched Successfully.',
    NO_IMAGE_FOUND: 'No Image Found'
    
}